default: &default  
adapter: mysql2  
encoding: utf8  
username: codeboxx  
password: Codeboxx1!  
host: codeboxx.cq6zrczewpu2.us-east-1.rds.amazonaws.com  
port: 3306  

 

development:  
<<: *default  
database: dominhannguyen


secondbase:
  development:
    adapter: postgresql
    database: dominhannguyen
  
